name: build
on: [push, pull_request]
jobs:

  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23.3
      uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: 1.23.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      
    - name: Test
      run: |
        go mod tidy -v
        go test -race ./...

    - name: Build
      run: go build ./...
